apiVersion: v1
kind: Service
metadata:
  name: argocd-service
spec:
  selector:
    app: argocd
  ports:
    - protocol: TCP
      port: 80 # Expose port 80 on the service
      targetPort: 8080 # Forward traffic to the container's port
  type: LoadBalancer # Use LoadBalancer for cloud providers that support it
